services:
  back-end:
    image: 0rf1az/flask-application:${VERSION?please set the version}
    networks:
      - full-stack
    ports:
      - 5000:5001
    secrets:
      - db_password
  db:
    container_name: mysql
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=flask-application
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
    networks:
      - full-stack
    secrets:
      - db_password


secrets:
  db_password:
    environment: "password"
