name: Flask Application CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - ic-devops-batch-04

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY_NAME: flask-application
  DEPLOYMENT_SERVER_IP: ${{ secrets.INSTANCE_IP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY_NAME }}
          tags: |
            type=sha,prefix=,suffix=
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
